module.exports = {
  CLIENT_TO_SERVER_JOIN_GAME: 'CLIENT_TO_SERVER_JOIN_GAME',
  CLIENT_TO_SERVER_START_GAME: 'CLIENT_TO_SERVER_START_GAME',
  CLIENT_TO_SERVER_QUIT_GAME: 'CLIENT_TO_SERVER_QUIT_GAME',
  CLIENT_TO_SERVER_USE_CARD: 'CLIENT_TO_SERVER_USE_CARD',
  CLIENT_TO_SERVER_DISCARD_CARD: 'CLIENT_TO_SERVER_DISCARD_CARD',
  SERVER_TO_CLIENT_JOIN_GAME: 'SERVER_TO_CLIENT_JOIN_GAME',
  SERVER_TO_CLIENT_PLAYER_LIST_UPDATE: 'SERVER_TO_CLIENT_PLAYER_LIST_UPDATE',
  SERVER_TO_CLIENT_START_GAME: 'SERVER_TO_CLIENT_START_GAME',
  SERVER_TO_CLIENT_UPDATE_DUNGEON_CARD: 'SERVER_TO_CLIENT_UPDATE_DUNGEON_CARD',
}